### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ipkpjersi** [p14/face-emotes#1]
I am using Ubuntu 22.04 with Node 18 and cannot compile emoji-mask (it throws errors when running npm run start). I have also tried Node 16 and Node 12 with no success.
 
After running the following commands:
```
git clone https://github.com/p14/emoji-mask.git
cd emoji-mask
npm install 
npm run start
```
It then throws the following error:
```
ERROR in src/App.tsx:4:20

TS2307: Cannot find module './components/loader' or its corresponding type declarations.
```

Here's the full error log: https://gist.github.com/ipkpjersi/b1fda686a7a5ad2471c5c8f0e588f90f

**Comment by p14** [comment]
@ipkpjersi I believe the issue might be with the capitalization of the "L" in  App.tsx on line 4. I was having a similar issue to that when setting that file up initially. Try seeing if it helps to change that line to this:
`import Loader from './components/Loader';`

**Comment by ipkpjersi** [comment]
Hey,

Yep, that was the issue! I've gone ahead and submitted a PR with the fix: https://github.com/p14/emoji-mask/pull/2

Cheers.

**Comment by p14** [comment]
Thank you!
